### ISSUE TITLE
Implementation - Abstractive Summarization

### ISSUE THREAD

**Issue by shijunil** [siddBanPsu/AbTextSumm#1] opened 2016-02-08 19:11 UTC
Hi 
I have a linux PC with with Ubuntu 14.01 installed. I m unable to install and run your code. Can you please provide the step by step commands for installing and running the Example.py file. Also where can i find the detailed report of your approach. I could not find the paper.
Regards
Shiju

**Comment by siddBanPsu** [comment] 2016-02-08 21:19
What issue are you facing? What exactly do you mean by "I m unable to install and run your code.". You need to have python and other dependencies as listed in the README file. https://github.com/siddBanPsu/AbTextSumm/blob/master/README.md

This is the link to the paper: http://ijcai.org/papers15/Papers/IJCAI15-174.pdf

I have received emails from others who said the code could be set up easily on their systems. Let me know if you continue facing other issues.

**Comment by shijunil** [comment] 2016-02-19 01:58
Thank you . Can you suggest me any paper or idea for comparing two sentences and merging them. If you have worked on some.

Regards
Shiju

**Comment by siddBanPsu** [comment] 2016-02-20 18:19
You can read papers on "Sentence fusion". You should get enough leads on google scholar. 

Particularly, this might be a good starting point: http://dl.acm.org/citation.cfm?id=1108996

I am closing this issue because it is not really clear what the issue is. Let me know if there are other questions.

**Closed as completed by siddBanPsu** 2016-02-20 18:19 UTC
